### ISSUE TITLE
Page 367: Listing 11-19 refers to non-existant identifier "my_alloc".

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#100]
It appears that this is an undefined variable name, a typo.

I suspect that you intended to instead write `alloc`, since there *is* a variable nearby with that name and you do also use the name `alloc` in the discussion text that follows.

(PS: I'm reading the Amazon Kindle ebook version, if that makes a difference.)

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
