### ISSUE TITLE
Page 385: TEST_CASE in example code uses invalid delimiters symbols (+) for string.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#101]
One of the examples on the page has the following TEST_CASE line in it:

`TEST_CASE(+boost::gregorian::date supports periods+) {`

For some strange reason, this example attempts to use "+" as the delimiter symbol for strings, even though of course the correct delimiter is quotation marks.

PS: As always, the version that my reports are based on is the Amazon Kindle ebook version, since that's the version of the book that I bought.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
