### ISSUE TITLE
Page 391: Text refers to non-existant variable "time_per_addition".

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#102]
The error is from the following paragraph:

> Once the block completes, stopwatch destructs. This writes the duration of stopwatch to elapsed, which you use to compute the average number of nanoseconds per loop iteration and store into the **time_per_addition** variable ➏. You conclude the program by printing time_per_division with printf ➐.

(I'm reading the Amazon Kindle ebook version, as always with my reports.)

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
