### ISSUE TITLE
Page 433: Description of bs.flip(i) function of bitset is wrong.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#105]
In the table of operations for std::bitset:

> Flips the i-th bit **to zero**. Performs bounds checking; throws std:: out_of_range.

Should probably instead say either:

> Flips the i-th bit. Performs bounds checking; throws std:: out_of_range.

or:

> Flips the i-th bit (0 becomes 1; 1 becomes 0). Performs bounds checking; throws std:: out_of_range.

depending on preference.

(As usual, I'm on the Kindle ebook version.)

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
