### ISSUE TITLE
Page 459 and 462: Exercises 13-1 and 13-4 are exact duplicates of each other. The exercise list also includes an unnumbered exercise at the end.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#106]
On page 459, exercise 13-1 and 13-4 are exact duplicates. 

There is however also an unnumbered exercise appended to the end of the exercise list (on page 462) as if it were part of exercise 13-6 when it is clearly not. The unnumbered exercise has the following text:

> Implement a Matrix class like SquareMatrix in Listing 13-38. Your Matrix should allow unequal numbers of rows and columns. Accept as your constructor’s first argument the number of rows in Matrix.

It seems highly likely to me that this unnumbered exercise is closely related to the duplicate exercise, but I could be wrong. There could be both a missing exercise 13-4 and also the unnumbered exercise, or it could be that the unnumbered exercise was supposed to be where the duplicate was etc.

(As usual, I'm on the Kindle ebook version.)

...

On a more personal note: 

I just want to say that I'm really enjoying your book and that it's one of the better programming books I've ever read. It's proving very useful for updating my C++ skills to be more modern (last time I read a C++ book was from a book published in 2003... lol... I'm so out of date). The book is very good. It just has a bunch of careless errors and minor editorial problems, all of which are easy to spot and disregard if one has at least intermediate experience in programming.

Anyway, I just wanted to say that since I get tired of feeling so negative all the time posting a bunch of minor careless errors. Have a good day/week etc.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade! I really appreciate all the effort you're putting into making future printings/revisions better. Could you send me an email if you don't mind? ccc@lospi.net
