### ISSUE TITLE
Page 495: Missing text formatting for "this" makes one of the sentences confusing.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#110]
In the following text:

> The find_first_of function accepts a string and locates the first character in this contained in the argument.

The word "this" should probably be formatted to make it clearer that it refers to `this` as in a pointer to the current object.

As it currently stands, an initial reading of the sentence makes the sentence seem grammatically incorrect at first glance.

Oh, and I'm on the Kindle ebook version, as usual.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!

**Comment by thederz** [comment]
FYI, this issue shows up on p. 496 of the printed version
