### ISSUE TITLE
Page: 507: Description of mr.format(str) probably has an error in it.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#111]
The description reads:

> Returns a string with contents according to the format string str. There are three special sequences: **$'** for the characters **before** a match, **$'** for the characters **after** the match, and $& for the matched characters.

Notice that $' occurs twice, both for the "before" and "after" cases. I'm unfamiliar with these operators, but this seems highly unlikely to be correct as written.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade! This appears to be an issue with the font. These should be "acute"/"grave" accents ` and ´.
