### ISSUE TITLE
Page 519: Description of the meaning of fnd in find(s, fnd) is missing from the paragraph before the table.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#114]
Notice that the preceding paragraph never describes what "fnd" means:

> In this table, **s**, **s1**, and **s2** are strings; **p** is an element comparison predicate; **rgx** is a regular expression; and **n** is an integral value.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
