### ISSUE TITLE
Page 548, Listing 16-9, GitHub code: Provided code for example omits sign from cout for seekg.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#116]
In the provided GitHub source code for Listing 16-9, the following code occurs:

```
    intro.seekg(-4, ios_base::end);
    cout << "tellg() after seekg(4, ios_base::end): " << intro.tellg() << endl;
    cout << "Contents after seekg(4, ios_base::end): " << intro.rdbuf() << endl;
```

Notice that it says "seekg(**4**, ios_base::end)" (which is wrong) instead of ""seekg(**-4**, ios_base::end)" (which is correct).

This time, the Kindle book has the correct text (-4) but the GitHub code is wrong.

The lack of a negative sign here in the GitHub code would be confusing for users of the provided code.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
