### ISSUE TITLE
GitHub code for Listing 17-1, for Page 552: Name of test case in code sample doesn't match name in book and doesn't make sense.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#117]
The test case in the book for Listing 17-1 looks like this (which makes sense):

`TEST_CASE("std::filesystem::path supports == and .empty()")`

... but the GitHub code in "filesystem.cpp" looks like this (which is doesn't make sense in context):

`TEST_CASE("ostringstream produces strings with str")`

Thus, it appears to probably be a copy paste error.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
