### ISSUE TITLE
Page 561 (Kindle ebook only): Has typo "tect".

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#118]
In the following text from the page:

> last_write_time( p, [t] [ec]), which, if **tect** is provided, sets p’s last modified time to t; otherwise, it returns the last time p was modified. (t is a std:: chrono:: time_point.)

Notice the erroneous "tect" text error.

The paper version of the book doesn't have this error.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
