### ISSUE TITLE
Page 570: Exercise 17-2 contains a nonsensical/ungrammatical phrase "perform a recursive directory"

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#120]
In the following text:

> 17-2. Improve the program in Listing 17-8 so it can take an optional second argument. If the first argument begins with a hyphen (-), the program reads all contiguous letters immediately following the hyphen and parses each letter as an option. The second argument then becomes the path to search. If the list of options contains an R, **perform a recursive directory**. Otherwise, don’t use a recursive directory iterator.

This phrase should probably instead be something like "perform a recursive directory [search/listing/etc]". I.e. replace the expression in [ ] with whatever your intent was.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
