### ISSUE TITLE
Error in 2_23.cpp

### ISSUE THREAD

**Issue by rush4ratio** [JLospinoso/ccc#121]
Line 30 in 2_23 works for me when instead of curly braces, I use parenthenses (i.e. ())

**Comment by WraithGlade** [comment]
I tested the listing you mentioned by grabbing the code from https://github.com/JLospinoso/ccc/blob/master/chapter_2/listing_2_23.cpp and compiling it on Visual Studio 2019 and it worked for me without needing to use parentheses.

I also checked both the ebook and the print version of the book and cannot find any anomalies.

What compiler are you using?

For reference, I have C++17 language support enabled on my compiler, so I suppose it's possible that could be influencing the outcome. Visual Studio 2019 doesn't enable C++17 by default. You have to enable it in the project properties. Not sure if that's relevant though. It's something to try though potentially.

(PS: I'm not the author. I'm just another reader.)

**Comment by rush4ratio** [comment]
I appreciate the response. 
After trying and failing by typing, I copy/pasted 2_23.cpp and it still didn't work.
I'm using a mac and therefore compiling with clang++ version 9.0.0

**Comment by WraithGlade** [comment]
What is the error message the compiler is giving you?

**Comment by rush4ratio** [comment]
Ahhh...thanks, specifying the flag -std=c++11, helped me. I think the author should consider adding that detail in code examples -- a minimum c++ standard required.

**Comment by WraithGlade** [comment]
Glad to hear it helped.

You should probably set the standard to higher than C++11 though, by the way. Later in the book you'll use some stuff that depends on newer versions, and the newer versions like C++17 are much better in many respects.
