### ISSUE TITLE
Page 574: The phrasing of the quadratic example makes it sound like all polynomial complexity is quadratic complexity, which is wrong and misleading.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#123]
From the following text:

> **Polynomial (or quadratic) time O(N^2)** About 99,000,000 additional computations. An example is comparing all the elements in a collection with all the elements in another collection.

The way "Polynomial (or quadratic)" is phrased here is very likely to confuse or mislead readers that aren't already familiar with the subject matter. It makes it sound like all polynomial complexities are quadratic complexities. It makes it sound like "polynomial" and "quadratic" are 100% synonymous and equivalent in both directions. Only someone who already understands complexity theory will be able to understand what is actually intended here.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
