### ISSUE TITLE
Page 584 (Kindle ebook): Formatting of whitespace for find_first_of example causes problems for many width settings.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#125]
It should probably be changed to not be indented so far over.

See the attached screenshot.

![find_first_of bad formatting](https://user-images.githubusercontent.com/8360085/72748079-4fdfa480-3b84-11ea-945e-8a77b41bddb5.jpg)

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade! I've noted this for future revisions.
