### ISSUE TITLE
Page 596: Description of move from <algorithm> has typos in it.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#128]
In the following text from the page:

> The result is that the elements of **detector1** are in a moved from state ➐ ➑ and **the elements of detector2 are moved into detectors2** ➒ ➓.

There are two typos (or 3 depending on how you count it) here:

(1) "detector1" should be "detector**s**".

(2) "the elements of **detector2** are moved into detectors2" should be "the elements of **detectors1** are moved into detectors2

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade! 

So I believe (1) is correct: detector2 isn't in a moved-from state. Do I misunderstand? (2) is definitely a typo.

**Comment by JLospinoso** [comment]
I see it now, thanks. :)
