### ISSUE TITLE
Page 604: Example code for "remove" from <algorithm> differs in book and GitHub.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#131]
Compare the code on GitHub for the "remove" test case from:

https://github.com/JLospinoso/ccc/blob/master/chapter_18/algorithms.cpp

... with that of page 604 in the ebook and paper book.

The ebook and paper book use "erase" to do the erasing, but the GitHub code uses "resize" instead.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
