### ISSUE TITLE
Page 606: The GitHub code for "unique" from <algorithm> does not exist on GitHub.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#132]
See https://github.com/JLospinoso/ccc/blob/master/chapter_18/algorithms.cpp

The code for "unique" test case should be right after the code for the "remove" test case, but it doesn't exist anywhere in any of the chapter 18 example code on GitHub.

**Comment by WraithGlade** [comment]
Here is a copy of the code for it though, which I extracted and cleaned up from Kindle myself:

```
TEST_CASE("unique") 
{ 
	string without_walls = "Wallless"; 
	
	const auto new_end = unique(without_walls.begin(), without_walls.end()); 
	without_walls.erase(new_end, without_walls.end()); 
	
	REQUIRE(without_walls == "Wales"); 
}
```

Perhaps that will save other readers some time.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
