### ISSUE TITLE
[Could easily not be an error, but reporting just in case.] Page 638: Chapter 18 has no exercises at the end.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#139]
Every other chapter up to this point has had exercises.

However, the omission of exercises from Chapter 18 could easily be intentional, since the breadth of the subject matter for algorithms is quite huge. 

I just thought I'd send in this report anyway just in case perhaps the exercises were accidentally cut out. It may be that this is just an intentional design decision, which is perfectly fine if so.

**Comment by JLospinoso** [comment]
Thanks! Yes it's intentional -- the chapter is enormous and functions mainly like a quick reference.
