### ISSUE TITLE
Page 705: Sentence before Listing 21-12 seems wrong.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#143]
From the text:

> Listing 21-12 provides a snippet that you could append into main after Listing 21-10 to parse results into a variables_map.

Notice that this text is nearly identical to the sentence just before the prior Listing 21-**11**.

The corresponding code for Listing 21-12 seems to be about retrieval, not parsing, from what I can see. I might be wrong though. Perhaps it is still doing some parsing then.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
