### ISSUE TITLE
Page 367: Typo in return value of operator!=

### ISSUE THREAD

**Issue by danzek** [JLospinoso/ccc#145]
The top of p. 367 (print edition) indicates that both `operator==` and `operator!=` return `true`, but in Listing 11-18 the latter returns `false`.

**Comment by danzek** [comment]
Also, I’ve been only posting substantive typos, by which I mean that they could cause confusion (granted, both typos I’ve reported thus far have been minor). I’ve also identified:

- simple grammatical typos (e.g., “that share some a common theme...” on p. 311), 
- simple formatting issues (e.g., no spaces between the typename, ellipsis (`...`), and the variable name in the parameter pack pattern/example in Listing 9-7 on p. 252), and
- a potentially unfinished example (e.g., the comment indicating “TODO” on p. 207).

I haven’t bothered reporting these as they are so minor (for all I know, the last one in this list may have been intentional). Do you want me to stay on my current path (only reporting more substantive typos) or would you prefer I also report these very paltry typos as well (with the caveat that I’m not going to reread the past 370+ pages to find them again, so I’ll only report new ones going forward)?

I don’t want to waste your time, but if No Starch Press intends to print another edition with these fixed (or you find time to update the book for C++20 in the next few years :P), it takes me very little time to report them on my phone.

**Comment by JLospinoso** [comment]
Thanks, @danzek! I'll have a look at these others
