### ISSUE TITLE
Page 253 - Fold Expressions parameter pack name wrong

### ISSUE THREAD

**Issue by nicebub** [JLospinoso/ccc#147]
I believe that in the text under the Fold Expressions heading:
  "For example, you could employ the following fold expression to sum over all elements in a parameter pack called 'pack'"
--------------------------------------
(... + args )

does the earlier sentence with the parameter-pack named 'pack' refer to the following expression
with 'args' as the name of the pack? 
If so then one should be changed.

Thank you.

**Comment by JLospinoso** [comment]
Thank you, @nicebub!
