### ISSUE TITLE
Page 252: Listing 9-7 improper spacing

### ISSUE THREAD

**Issue by nicebub** [JLospinoso/ccc#148]
In Listing 9-7
It appear that there is no space between between the ellipses and the argument names. 
ie. “typename...Args” instead of “typename... Args”
As well as “Args...args” instead of “Args... args”
This does not appear to be the case and is fixed with the same code in Listing 9-6 and Listing 9-8.

**Comment by JLospinoso** [comment]
Thanks, @nicebub!
