### ISSUE TITLE
Pages 326 ,331 ,333 , and 335 extra '<' in template usage

### ISSUE THREAD

**Issue by nicebub** [JLospinoso/ccc#149]
There is an extra '<' when defining a template argument.  looking like << .... >

page 326: Listing 10-48: 
 ::testing::NiceMock<<MockServiceBus> nice_mock;
 ::testing::StrictMock<<MockServiceBus> strict_mock;

should be 
 ::testing::NiceMock<MockServiceBus> nice_mock;
 ::testing::StrictMock<MockServiceBus> strict_mock;

page 331: Listing 1-54:

in the struct NiceAutoBrakeTest : ::testing::Test
NiceMock<<MockServiceBus> bus;

should be 
NiceMock<MockServiceBus> bus;

in struct StrictAutoBrakeTest : ::testing::Test
StrictMock<<MockServiceBus> bus;

should be 
StrictMock<MockServiceBus> bus;

page 335: Listing 10-55

In TEST_CASE("AutoBrake")

auto* bus = mocks.Mock<<IServiceBus>();
should be
auto* bus = mocks.Mock<IServiceBus>();

**Comment by JLospinoso** [comment]
Hi @nicebub! Thanks so much for posting. I'm unable to find the extra < ... which format are you on? I checked paper book and the epub.

**Comment by nicebub** [comment]
After reviewing the paperback book of which I have in my possession, with more magnification I could see that I was in err.  At closer inspection I realize that the extra '<' is in fact just the end of the 'k' in 'Mock', thus making it appear that there are two '<' in a row.  This is not the case and therefore an inaccurate bug submission..

**Comment by JLospinoso** [comment]
Ok, thanks so much @nicebub! Hope you're enjoying the book 😃
