### ISSUE TITLE
Listing 4-5 "const char* const name;"

### ISSUE THREAD

**Issue by a9ma8s** [JLospinoso/ccc#151]
If I'm not mistaken it should read
`const char* name;`

instead of 
`const char* const name;`

**Comment by JLospinoso** [comment]
Hi @a9ma8s, thanks for the comment! 

Both `const char* name` and `const char* const name` are correct. Both make the pointed-to element `const`, while only the latter makes the pointer `const` as well. 

I'll make a note that, for future printings/revisions, I should present the.`const TYPE* const` construction somewhere :)
