### ISSUE TITLE
Description for Listing 4-25. Incorrect number. 

### ISSUE THREAD

**Issue by a9ma8s** [JLospinoso/ccc#152]
The description for Listing 4-25 says: 
You can use array new (1) to initialize buffer because you know `other.max_size` is greater than 0. 

But the correct number is (2) so the sentence would say: 
You can use array new **(2)** to initialize buffer because you know other.max_size is greater than 0.

**Comment by JLospinoso** [comment]
Thanks, @a9ma8s!
