### ISSUE TITLE
Question: Lambda expression in Listing 10-17

### ISSUE THREAD

**Issue by a9ma8s** [JLospinoso/ccc#155]
Previously I learned in the book that `auto_break ` from Listing 10-17 can be invoked e.g. with `auto_break(BreakCommand{ time_to_collision })`. But why is `auto_break `also invoked in Listing 10-18 because of `publish(BreakCommand{ time_to_collision })`?

**Comment by a9ma8s** [comment]
Ok I understand now. I mistook `auto_brake` for a lambda, but its constructor *takes* a lambda as a reference to the publish method of the bus. And when this publish method (the lambda passed as a parameter) gets invoked, the `brake_commands_published` is incremented.

**Comment by JLospinoso** [comment]
Hi @a9ma8s, no problem! Hope you're enjoying the book and please let us know if you run into any other issues :)
