### ISSUE TITLE
Typo in Listing 3-1?

### ISSUE THREAD

**Issue by scortus** [JLospinoso/ccc#156]
You indicated that you declare a pointer by _appending_ an asterisk to the pointed-to type (e.g., int* my_ptr;), but in Listing 3-1(pg. 68), the asterisk is _prepended_ to 'gettysburg_address' instead of being appended to its type.  Is this a typographical error?

**Comment by JLospinoso** [comment]
Hi @scortus, thanks for posting! Actually these are both correct and just a matter of style. I've got a note here to mention this in future editions.
