### ISSUE TITLE
Exercise Solutions?

### ISSUE THREAD

**Issue by robml** [JLospinoso/ccc#157]
I have loved this book and it has greatly helped me in my journey in learning C++. Having spent time going over the book thoroughly by myself, I realize I often have few places to turn if I have specific questions regarding the book. These mostly come up in the exercises, which I find fascinating and equally challenging. However I am, nonetheless, still confused by some. I know it is not required to post Exercise solutions, but can we ask if we have any questions anyways? For me it was Chapter 5 that got me and the implementation of the Accounting Database, where I started asking questions of how I could store the number of accounts before declaring the InMemoryAccountDatabase given that C++ is a strongly typed language. I come from a Python and Data Science background so there has been a learning curve, all other resources online point to existing libraries or unrelated resources, but that does not help me (and other readers I have seen on Reddit) to really learn and experiment like a student would be able to in a classroom. This post is getting quite long, but I hope that someone looks into this and is willing to work on this together!
Best,
Rob

**Comment by JLospinoso** [comment]
Hi @robml, thanks so much for reaching out! I've got a note here for future editions. I think having exercise solutions would be really welcomed.
