### ISSUE TITLE
Chapte 10, Listing 10-8 Code Error

### ISSUE THREAD

**Issue by robml** [JLospinoso/ccc#158]
Recently was going through the AutoBrake example in Chapter 10 of the book. Everything seems to be alright, however my IDE (Visual Studio) highlights an error in the unit tests, namely when I try to instantiate the AutoBrake class necessary to call on the `struct`'s internal functions. I believe the problem is because AutoBrake is a template class, because when the unit tests try to instantiate it, the error that is returned is `argument list for class template "AutoBrake" is missing`. If anyone has run into a similar problem would love to share. (NOTE: the code in the book I am referring to is different from that on Github).

**Comment by JLospinoso** [comment]
Hi @robml, thanks for the note! I *think* this is an issue to do with "Class template argument deduction." C++17 supports this--could you verify that your Visual Studio is up-to-date? You may also need (to enable C++17)[https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019].

**Comment by robml** [comment]
Hi @JLospinoso , that seems to have done the trick! Visual Studio was up-to-date, but I had to enable C++17 manually in the configuration properties. It also seems to work no problem with the /std:latest (which supposedly is C++20) so good to see compatibility there. Thanks again!
