### ISSUE TITLE
On p. 91, rat_things_power

### ISSUE THREAD

**Issue by bliutwo** [JLospinoso/ccc#163]
> The variable `rat_things_power` is a static variable because it's declared at global scope with the `static` keyword. **Another feature of being declared at global scope is that `power_up_rat_thing` can be accessed from any function in the translation unit.**

I believe in this context, you meant to write `rat_things_power` instead of `power_up_rat_thing` since we are talking about how `rat_things_power`, the static variable, can be accessed from any function in the translation unit (functions such as `power_up_rat_thing()`)?

**Comment by JLospinoso** [comment]
Thanks, @bliutwo! You're absolutely right.
