### ISSUE TITLE
8-28 Listing Errata

### ISSUE THREAD

**Issue by bliutwo** [JLospinoso/ccc#166]
Hello,

You have this fixed in your [GitHub listing of 8-28](https://github.com/JLospinoso/ccc/blob/master/chapter_8/listing_8_28.cpp#L40), but on p. 237, I noticed that the listing has `const auto x = range.begin()` instead of `auto x = range.begin()`, which you fixed [here](https://github.com/JLospinoso/ccc/blob/master/chapter_8/listing_8_28.cpp#L40).

However, I noticed that your errata/typos on your [website](https://ccc.codes/) don't mention this. I don't know if this is intentional, but I think it would be helpful to have a note about it there.

Thanks for your great book!

**Comment by JLospinoso** [comment]
Thanks, @bliutwo! I'm really glad you're enjoying the book :)
