### ISSUE TITLE
Typo - Chapter 1 - Installing GCC and Clang on Debian / Step 4. Test GCC and Clang:

### ISSUE THREAD

**Issue by geektechdude** [JLospinoso/ccc#167]
Apologies if this is the wrong place for typos but I think:

$ g++-8 –version

should be:

$ g++-8 –-version

Currently reading via O'Reilly online (ordered the paperback, it's due over weekend) so can give the page number then if needed.

**Comment by JLospinoso** [comment]
Thanks, @geektechdude!
