### ISSUE TITLE
Configuring Google Testing guide

### ISSUE THREAD

**Issue by bliutwo** [JLospinoso/ccc#168]
Hello,

This is not really an issue with your book, but I made a [short, quick-start guide](https://github.com/bliutwo/google_test_guide#instructions-for-google-c-testing-for-dummies-unix-edition) on configuring Google Test (on Unix). Maybe this would be useful to future readers.

Thanks!

**Comment by JLospinoso** [comment]
Thanks, @bliutwo! I've added a link to the site.
