### ISSUE TITLE
www.arcyber.army in Ch. 20 has moved permanently

### ISSUE THREAD

**Issue by Dinglebarry9** [JLospinoso/ccc#175]
They moved to https://www.arcyber.army.mil but when I try that with https there is an error

**Comment by JLospinoso** [comment]
Hi @Dinglebarry9! Thanks. It's good to see that they've moved to TLS. Unfortunately, the example won't work with TLS so I'll have to add a note to the site indicating to use a different URL (one that supports non-TLS HTTP).
