### ISSUE TITLE
Listing 4-38 parentheses vs brackets

### ISSUE THREAD

**Issue by kwadsten** [JLospinoso/ccc#18]
Hi, in example 4-38 the move constructor uses ( ) for initialization instead of { } that the copy constructor uses.  Is this intentional?  I thought { } style was recommended.

**Comment by JLospinoso** [comment]
Hi @kwadsten, you're right! That's a typo. It's correct in Listing 4-35. I've added this to the errata.

"We're sorry for the inconvenience." 😂
