### ISSUE TITLE
Page 96, `delete[] my_int_ptr` s/b `delete[] my_int_array_ptr`

### ISSUE THREAD

**Issue by adem** [JLospinoso/ccc#180]
In the **Dynamic Storage Duration > Dynamic Arrays** section, the example for deallocating the previously allocated `my_int_array_ptr` reads `delete[] my_int_ptr`.

Instead, it should read `delete[] my_int_array_ptr`.

**Comment by JLospinoso** [comment]
Thanks, @adem!
