### ISSUE TITLE
Listing 2-2 is not consistent with the prose following it

### ISSUE THREAD

**Issue by ttmc** [JLospinoso/ccc#181]
The following is true of the EPUB version of the book that I got from nostarch.com in July of 2020. I don't know if it's true of any other version.

Listing 2-2 contains the line:

https://github.com/JLospinoso/ccc/blob/369b295d887708204f1820ba7df27c8e40c7296b/chapter_2/listing_2_2.cpp#L7

but the prose following Listing 2-2 (describing the output when running the compiled Listing 2-2) says, "...yielding the message `There are 69,105 leaves in here`". The prose added an extra word: `in`

**Comment by adem** [comment]
Looks correct in the PDF version.

**Comment by JLospinoso** [comment]
Thanks, @adem!
