### ISSUE TITLE
Chapter 4, page 108, listing 4-15: wrong `num` argument value

### ISSUE THREAD

**Issue by Augustin-Zidek** [JLospinoso/ccc#182]
Hi Josh,

thanks for you great book on C++. I am reading it now and it reads like a novel :). 

I think the following line in listing 4-15 on page 108 (Appending and Printing)

```
std::strncpy(buffer + length, x, max_size - length)
```

should be instead

```
std::strncpy(buffer + length, x, x_len)
```

since we want to copy only `x_len` bytes from `x`.

**Comment by JLospinoso** [comment]
Hi @Augustin-Zidek, thanks for the note! We use the third argument is a "safety argument" which specifies a maximum number of bytes to copy. Here we use `max_size-length` because this ensures `strncpy`doesn't go past the end of `buffer`. Does that make sense?

**Comment by Augustin-Zidek** [comment]
I see, that makes sense, thanks for the clarification. 

It would be good to clarify it in the book somehow as well though, as my initial though when reading it was that we are (inefficiently) copying `max_size - length` bytes even if there are less in the `x` buffer. I think using `std::min(x_len, max_size - length)` might make it slightly clearer.
