### ISSUE TITLE
Typo: va_args should be va_arg (singular)

### ISSUE THREAD

**Issue by michaeldperez** [JLospinoso/ccc#183]
In chapter 9, page 251 of the "Variadic Functions" section, there are two bullet points describing problems with the use of variadic functions. The first reads "Variadic arguments are not type-safe. (Notice that the second argument of `va_args` is a type.)" I believe it should read "...Notice that the second argument of `va_arg` is a type.)" i.e. `var_arg` should be singular.

**Comment by JLospinoso** [comment]
Thanks, @michaeldperez!
