### ISSUE TITLE
Typo: Page no. 577 - any_of algorithm description

### ISSUE THREAD

**Issue by vaibspider** [JLospinoso/ccc#186]
On page no. 577, in the any_of algorithm description, following sentence is present.
> The algorithm returns **false** if the target sequence is empty or if pred is true for any element in the sequence; otherwise, it returns false

Instead of false(highlighted above), it should be true.

**Comment by dascandy** [comment]
any_of returns false if the sequence is empty: https://en.cppreference.com/w/cpp/algorithm/all_any_none_of

The sentence can be reworded to be clearer, that's true.
