### ISSUE TITLE
Dedication - Incorrect Number of rounds

### ISSUE THREAD

**Issue by jwobser** [JLospinoso/ccc#197]
```cpp
auto i {0x01B99644};
```
Results in: orDFanielle

Changing to `0x1A2664` gets the correct result. And runs 16x fewer rounds!

**Comment by JLospinoso** [comment]
Interesting; which compiler are you using?

**Comment by jwobser** [comment]
My laptop is out of juice at the moment, so I just re-typed it at [Godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:21,endLineNumber:8,positionColumn:21,positionLineNumber:8,selectionStartColumn:21,selectionStartLineNumber:8,startColumn:21,startLineNumber:8),source:'%23include+%3Calgorithm%3E%0A%23include+%3Ciostream%3E%0A%23include+%3Cstring%3E%0A%0A%0Aint+main()%7B%0A++++auto+i+%7B0x01B99644%7D%3B%0A++++std::string+x%7B%22+DFaeeillnor%22%7D%3B%0A++++while+(i--)+std::next_permutation(x.begin(),x.end())%3B%0A++++std::cout+%3C%3C+x%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang1300,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'x86-64+clang+13.0.0+(C%2B%2B,+Editor+%231,+Compiler+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+13.0.0+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) and it worked fine.

I think what I did is omit the leading " " (space), because when I run that I get the same incorrect result I originally reported.

My mistake! I'll close.

I love the book, btw!

**Comment by MrO-007** [comment]
Thank you so much I was wondering what I did wrong, I am using the embarcadero IDE
