### ISSUE TITLE
Incorrect info: Page 61

### ISSUE THREAD

**Issue by BlessedOneKobo** [JLospinoso/ccc#200]
```
struct PodStruct {
uint64_t a;
char b[256];
bool c;
};
```

> You can only omit fields from right to left, so the following won’t compile:
> `PodStruct initialized_pod4 = { 42, true };`

Program compiles and initializes `b` to ASCII character **SOH**. Compiled with -std=c++17 using g++9.3

GDB Output:
`$1 = {a = 42, b = "\001", '\000' <repeats 254 times>, c = false}`

**Comment by JLospinoso** [comment]
Thanks! Yes, `b` initializes with an implicitly cast `bool`. I will rephrase to indicate this is "probably not what the programmer intends."
