### ISSUE TITLE
Page 18, last note

### ISSUE THREAD

**Issue by alfredmyers** [JLospinoso/ccc#206]
Page 18, last note

> The printf function is a derivative of the writef function offered in BCPL, a defunct
programming language designed by Martin Richards in 1967. Providing the specifiers
%H, %I, and %O to writef resulted in hexadecimal and octal output via the functions
WRITEHEX, WRITED, and WRITEOCT. It’s unclear where the %d specifier comes from (perhaps
the D in WRITED?), but we’re stuck with it.

The letter **D** in `WRITED` and `%d` stands for **decimal**.

**Comment by JLospinoso** [comment]
"perhaps" 🙂
