### ISSUE TITLE
Page 79, first paragraph after Listing3-10

### ISSUE THREAD

**Issue by alfredmyers** [JLospinoso/ccc#207]
Where read:
> ... The element trooper1 is
assigned the operating number TK-421, and then you insert **it** as the next
element in the list.

Should read:
> ... The element trooper1 is
assigned the operating number TK-421, and then you insert **trooper2** as the next
element in the list.

**Comment by JLospinoso** [comment]
trooper1 is the inserted element, not trooper2.
