### ISSUE TITLE
p. 160 default and non-default constructor

### ISSUE THREAD

**Issue by indruckbalazs** [JLospinoso/ccc#213]
Hi,

In the third edition on page 160 there is a remark: "(Recall from Chapter 4 that you need default when you want both a default constructor and a non-default constructor.)"

I think this is wrong here as in Chapter 4 copy and move constructors are discussed along with the destructor. Even in the table on page 130 there isn't any default constructor discussed.

I've tried to search for it up until page 160, but I think this part is missing from the book and I think it is a little bit misleading.

Best regards,
Balazs

**Comment by JLospinoso** [comment]
Hi @indruckbalazs -- thanks very much for the comment! You're right, this is an oversight. I'm working on a revision and will incorporate a better discussion of `default` into Chapters 2&4.
