### ISSUE TITLE
Question about the book

### ISSUE THREAD

**Issue by ghost** [JLospinoso/ccc#214]
Please tell me, is there somewhere your solutions to the problems that you are asking? I would like to rely on something when solving, as well as see how a professional solved such a problem and compare his solution with yours

**Comment by MatthewVasseur** [comment]
In a [previous question #157](https://github.com/JLospinoso/ccc/issues/157) Josh mentions that solutions to the exercises might be in a future edition

**Comment by JLospinoso** [comment]
Thanks, yes that's true @MatthewVasseur
