### ISSUE TITLE
listing_8_27 does not compile

### ISSUE THREAD

**Issue by mwheaton** [JLospinoso/ccc#22]
listing_8_27 gives the following error message:

$ g++ -o fib listing_8_27.cpp
listing_8_27.cpp: In function ‘int main()’:
listing_8_27.cpp:38:43: error: inconsistent begin/end types in range-based ‘for’ statement: ‘FibonacciIterator’ and ‘int’
   for(const auto i : FibonacciRange{ 5000 }) {
                                           ^
listing_8_27.cpp:38:43: error: conversion from ‘int’ to non-scalar type ‘FibonacciIterator’ requested
listing_8_27.cpp:38:43: error: no match for ‘operator!=’ (operand types are ‘FibonacciIterator’ and ‘FibonacciIterator’)
listing_8_27.cpp:4:8: note: candidate: ‘bool FibonacciIterator::operator!=(int) const’
   bool operator!=(int x) const {
        ^~~~~~~~
listing_8_27.cpp:4:8: note:   no known conversion for argument 1 from ‘FibonacciIterator’ to ‘int’
/home/mwheat/downloads/ccc-master/chapter_8

$ g++ --version
g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)

**Comment by JLospinoso** [comment]
Thanks, @mwheaton! So you'll need to enable C++17 with the `-std=c++17` flag. 

https://gcc.gnu.org/projects/cxx-status.html

Can you verify that this solves the issue?

**Comment by mwheaton** [comment]
-std=c++17 does indeed fix the issue.  Thanks!

**Comment by JLospinoso** [comment]
No problem! Thanks for the feedback :-)
