### ISSUE TITLE
Page 353 "void fclose(FILE* close)" should be "int fclose(FILE* close)"?

### ISSUE THREAD

**Issue by Xupeiyi** [JLospinoso/ccc#28]
Page 353 "void fclose(FILE* close)" should be "int fclose(FILE* close)"?

**Comment by Xupeiyi** [comment]
And on Page 368 "11-1 Reimplement Listing 11-12 to use a std::shared_ptr ..." I guess that's "11-1 Reimplement Listing 11-13" by the way...

**Comment by JLospinoso** [comment]
Thank you, @Xupeiyi!
