### ISSUE TITLE
Listing 3-7 has the wrong memory position for letter_d and letter_D initialization

### ISSUE THREAD

**Issue by stanboya** [JLospinoso/ccc#35]
To make it equivalent to the listing 3-6, it should be:

char letter_d = *(lower + 3);           // lower decays into a pointer when we add
char letter_D = *(upper_ptr + 3);

instead of:

char letter_d = *(lower + 4);           // lower decays into a pointer when we add
char letter_D = *(upper_ptr + 4);

PS: Great book so far :)

**Comment by stanboya** [comment]
Did not see Issue #30. Sorry!

**Comment by JLospinoso** [comment]
@stanboya No problem, thanks so much for reporting! I hope you enjoy the rest of the book 😄
