### ISSUE TITLE
Listing11-10: Variable name mismatch with discussion in text

### ISSUE THREAD

**Issue by iskhanba** [JLospinoso/ccc#40]
Listing 11-10:
`auto son_of_arathorn{ std::move(aragorn) };`

**Discussion in text:**
Again, `aragorn` transfers ownership to `son_of_aragorn`. Because `son_of_aragorn` can own only one
dynamic object at a time, the move....

You probably meant `son_of_arathorn` or I am missing a new LOTR movie 😉.

**Comment by JLospinoso** [comment]
@iskhanba hahah great catch! Thank you 😂
