### ISSUE TITLE
Page 241 / Exercise 8-2: "exception" should read "expression"

### ISSUE THREAD

**Issue by thederz** [JLospinoso/ccc#46]
Exercise 8-2 reads: "**8-2**. Implement a `PrimeNumberRange` class that can be used in a range exception to iterate over all prime numbers less than a given value ..."

Exercise 8-2 should read: "**8-2**. Implement a `PrimeNumberRange` class that can be used in a range expression to iterate over all prime numbers less than a given value ..."

**Comment by JLospinoso** [comment]
Thanks, @thederz!
