### ISSUE TITLE
References appear to be unresolved

### ISSUE THREAD

**Issue by ffel** [JLospinoso/ccc#47]
Esp at the end of chap 6 and the beginning of chap 7 literature references appear to be unresolved,
for example:

- p. 178: [temp.res]
- p. 178: [temp.spec]
- p. 185: [expr.rel]

(in the pdf version)

**Comment by JLospinoso** [comment]
Hi, @ffel! Thanks so much for the issue. I understand how these might be confusing. On p. 29 it explains this notation is the ISO C++ Standard's method for referring to C++ Standard sections.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/147698/70240429-351fb080-173b-11ea-997e-ddd7d39d41d3.png">
