### ISSUE TITLE
Probably a typo: "mannie_service" vs "make_sentient" near Loc 660 in ebook.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#53]
The code example in Listing 4 says "mannie_service" as the names of the two overloaded functions, but later elaborations of the example use "make_sentient" instead. This seems like a likely typo.

Also, I have no idea what "mannie_service" is supposed to mean.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
