### ISSUE TITLE
There's a missing space in a code example, near Loc 1003 in ebook.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#55]
The code example for unique_ptr has a missing space for formatting:

"struct Foundation{" should be "struct Foundation {" to be consistent with the formatting of other parts of the book.

**Comment by WraithGlade** [comment]
The missing space also occurs again near Loc 1033 in ebook, in a following code example that uses the same struct.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
