### ISSUE TITLE
One of the sentences in the basic if/else-if/else condition section is confusingly worded.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#57]
The sentence "Only one of the three will be evaluated." near page 16 loc 1341 of the ebook could be worded better.

Between 1 and 3 of the condition branches will be evaluated, but only one of the code blocks will be run. The wording would best be changed to reflect that.

For example, you could instead say "Only one of the three [code blocks or compound statements etc] will be evaluated". This will improve clarity and reduce ambiguity.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
