### ISSUE TITLE
A pedantic point about the else block "always" executing... (not a big deal)

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#58]
In the text "the else clause’s statement-3 always executes" on/near page 16 in the ebook, technically this is false.

If one of the other conditions throws an exception the else block may not run. Not sure if you care about this pedantic point, because I understand your intent, but just wanted to point it out in case you care.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
