### ISSUE TITLE
Possible omission of a word in the note box for printf.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#59]
In the note box about the printf function on/near page 18 in the ebook, it seems like you may have omitted a word (not sure).

You say "hexidecimal and octal output" at one part in the text (which is two items) and then later say "WRITEHEX, WRITED, and WRITEOCT" (which is three items). These seem to be correleated/relative lists, but the former list has one less item and only WRITEHEX and WRITEOCT seem to be represented in the phrase "hexidecimal and octal output".

Thus, I suspect that you may have intended to write "hexidecimal, decimal, and octal output" in the former part instead. I don't know BCPL though at all, so maybe I'm wrong.

There definitely seems to be a subtle clarity problem going on here though.

Perhaps your editor/reviewer incorrectly deleted "decimal", falsely thinking it was redundant  when adjacent to "hexidecimal". A theory.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
