### ISSUE TITLE
Possible that you intended "INPUT-OUPUT" instead of "INPUT OUTPUT" on note box on page 18

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#60]
In my experience, it seems more common to write input-output as "input-output" instead of as "input output".

Perhaps you made a typo then, on the title "IOSTREAMS, PRINTF, AND INPUT OUTPUT PEDAGOGY" of the note box on/near page 18 in the ebook.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
