### ISSUE TITLE
Pedantic point: the note box about the use of "--snip--" should maybe come earlier in the book or not at all.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#61]
The note box text "Some listings in this book will build on one another. To save trees, you’ll see the use of the --snip-- notation to denote no changes to the reused portion." seems like it comes too late in the book.

It is already obvious by this point in the book that you are using "--snip--" that way. Thus, this note box should probably be either moved earlier in the book or deleted entirely.

The usage is pretty implicitly obvious, so deletion wouldn't be so bad. Subjective choice though, it does fit the surrounding discussion some.

Not a big deal. Just pointing it out.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
