### ISSUE TITLE
The wording of part of your description of comments is a bit wrong.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#62]
On/near page 21 in the ebook, the text "These symbols, // or /**/, tell the compiler to ignore everything from the first forward slash to the next newline" is not technically correct.

The way you have written it implies that both single line and multi-line comments "ignore everything from the first forward slash to the next newline", which is wrong. Only the single line comments do that.

Also, the compiler doesn't ignore everything from the *first* forward slash in "//", because in fact if you insert other text between the first "/" and the second "/" then it will try to parse the text as not being a comment. It's only after the entire "//" operator is written coherently that the subsequent text ignoring will occur.

Thus, you have two different aspects of this explanation in the text that are technically worded wrong.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade
