### ISSUE TITLE
Very subjective/pedantic point: phrasing of "search on your error messages online" maybe a bit odd. 

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#63]
In the note box on/near page 27 in the ebook, the phrasing of "search on your error messages online" seems maybe slightly odd to me.

Perhaps "search for" or "search for information about the error messages online" or something else might be better.

Very subjective/pedantic point. Seems like the clarity and wording semantics could be improved very slightly though.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
