### ISSUE TITLE
Possible typo in the "fundamental types" paragraph on/near page 31 of ebook.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#64]
The text "The sections that follow provide additional detail about these fundamental types." may have a typo on the word "detail". It seems like it would be better as "details".

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
