### ISSUE TITLE
Some grammatical errors in the text after the int type table on/near page 32 in ebook.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#65]
The text "Format specifiers appear here so you can print integers to console in examples to follow." should probably be something more like "Format specifiers appear here so [that] you can print integers to [the] console in [the] examples [that] follow.".

My suggested corrections appear in [] here.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
