### ISSUE TITLE
The suggestion to avoid using cstdint seems maybe ill advised.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#66]
I'm loving the book so far, but this suggestion you made to avoid using cstdint for types seems like it may be a bad idea to me. I was under the impression that cstdint works on virtually all major platforms (desktop, mobile phones, gaming consoles) and that it is usually far better to use it than the older naming conventions and far easier to port and work with. Only obscure embedded systems etc seem likely to lack these types. In fact, some more modern languages such as Rust design all their types to be more like cstdint, and it is is generally much better that way. The varying type sizes in original C++ are essentially a design flaw in the language

The specific text is "But because this header is not always available in every platform, you should only use cstdint types when there is no other alternative." on/near page 32 in the ebook.

I personally think cstdint should be used as much as possible pretty much. The only problem is interfacing with older code and making it readable with the differing type names.

This is just my opinion though, of course.

**Comment by JLospinoso** [comment]
I appreciate your opinion on this! Perhaps I'll present the other side of this argument in a future revision. Thanks!
