### ISSUE TITLE
Description of unary negation operator should probably have "bool" qualifier added to sentence.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#67]
On/near page 40 in the ebook:

"The unary negation operator (!) takes a single operand and returns its opposite. In other words, !true yields false, and !false yields true."

should probably instead be:

"The unary negation operator (!) takes a single **boolean** operand and returns its opposite. In other words, !true yields false, and !false yields true."

Obvious for an experienced programmer of course, but technically the operator can't just return the "opposite" of any type. It needs to be bool, so clarifying that would be more correct.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, there's a bit of nuance here. You don't have to give the unary negation operator a Boolean operand, just an expression that is convertible to a Boolean. (See e.g. p.203-204, "User-Defined Type Conversions"). I'm going to keep the wording as-is so as not to make the presentation too complicated for a beginner. Thanks!
