### ISSUE TITLE
Consider adding "standard" into std pronunciation note box as another option.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#68]
Besides hearing it pronounced as "S  T  D" and "stood", I've also heard std pronounced as just "standard" since that is what it actually stands for in a sense.

This is just a suggestion to add "standard" in as another possible pronunciation option that some people do use.

(page 41 in ebook)

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
