### ISSUE TITLE
Typo in size_t description section on/near page 41 of ebook (etc)

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#69]
The text "You use the size_t type, also available in the <cstddef> header, to encode size of objects." seems like it would be more correct if it was instead worded as "You use the size_t type, also available in the <cstddef> header, to encode **the** size of objects."

Also, the phrasing of the following sentence "The size_t objects guarantee that their maximum values are sufficient to represent the maximum size in bytes of all objects." also seems a bit odd. Perhaps a better way to phrase it would be "**Objects of type size_t** guarantee that their maximum values are sufficient to represent the maximum size in bytes of all objects.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
