### ISSUE TITLE
Explaination of array type is ambiguously worded on/near page 42 in ebook.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#70]
For the text "Array types include the contained type and the number of contained elements. You weave this information together in the declaration syntax: the element type precedes square brackets enclosing the array’s size." perhaps a better way of phrasing it would instead be something like this:

"Array types **require** the contained type and the number of contained elements **to be specified at initialization**. You weave this information together in the declaration syntax: the element type precedes **the identifier name and then the identifier name precedes the** square brackets enclosing the array’s size."

This is clearer and less ambiguous and more technically correct.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
