### ISSUE TITLE
Note box about expressions on/near page 44 comes across as disconnected from context. 

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#71]
The content of the note box is "You’ll learn about expressions in Chapter 7. For now, think of an expression as some bit of code that produces an effect on your program."

In the context, it isn't clear why this note box has been placed at this specific location. It doesn't feel connected to the surrounding text much. It should perhaps be re-worked into the text to make it sit in context better.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
