### ISSUE TITLE
Likely missing quotations around unicode English and Chinese examples on/near page 46.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#72]
The following block of text:

This code generates two variables: english, which contains A book holds a house of gold., and chinese, which contains the Unicode characters for 书 中 自 有 黄 金 屋.

should instead probably be written like this, to make the text boundaries clearer:

This code generates two variables: english, which contains "A book holds a house of gold.", and chinese, which contains the Unicode characters for "书 中 自 有 黄 金 屋".

I suppose you could argue this is a matter of taste, but using quotes is more logically clear and unambiguous.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks so much for reporting! I'd like to reserve the errata section for genuine errata rather than stylistic/editing points. But I will definitely keep this comment in mind for further printings/revisions of the book. Thanks.
