### ISSUE TITLE
Contrary to how it is worded, listing 2-12 does not show a "conversion" to uppercase.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#73]
Instead, it simply prints out all the lowercase letters and then all the uppercase letters.

This does not constitute a conversion, and thus the wording of the preceding text "Listing 2-12 shows how to build an array with the letters of the alphabet, print the result, and then **convert** this array to uppercase and print again." should technically be changed to reflect that.

Nit picky of course, but true. Hopefully I'm not overdoing these issue reports, but I figure I should do it while I'm reading the book or else I'll never end up reporting them. I hope it is helpful rather than merely annoying. I'm sure you'll be fine either way though.

**Comment by WraithGlade** [comment]
Oh, I just saw that you saw and handled a bunch of these reports. Didn't see that until just now.

**Comment by JLospinoso** [comment]
Thanks @WraithGlade! I really appreciate all the effort you've been putting into helping me make the book better :-)
