### ISSUE TITLE
Page 91 and 92: Threshold value in condition "waste_heat > 10000" and the value mentioned later in the text are not the same.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#74]
On page 91 the waste_heat threshold in the code is 10,000, but later in the text on page 92 it is instead described as having a threshold value of 1,000.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, I'm not sure I see where the text on Page 92 is incorrect. Are you referring to "Finally, you check whether waste_heat is over a threshold value
of 10000 (4)."? Thanks!

**Comment by JLospinoso** [comment]
I found it--oddly this typo isn't in the paper or PDF books. Thanks again.
