### ISSUE TITLE
Page 110: SimpleString is referred to incorrectly as being of type "string" in the parenthetical sentence.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#76]
The following text:

> (It’s your responsibility as a user of **string** to check for this condition.)

... should instead be this:

> (It’s your responsibility as a user of **SimpleString** to check for this condition.)

**Comment by JLospinoso** [comment]
Hi @WraithGlade, I think this could go either way: `string` refers to the object in Listing 4-16 while `SimpleString` refers to its type. I'll make the change for clarity's sake. Thanks!
