### ISSUE TITLE
Page 112 refers to a non-existant function "fn()" in the text.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#78]
On page 112, the text describes the call stack as being:

`fn() → fn_b() → fn_c()`

However, this is wrong. There is no function named `fn()` defined anywhere in the given source code.

A better way to describe the call stack at that time would be:

`main() → fn_b() → fn_c()`

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
