### ISSUE TITLE
Page 137 of ebook: Hyperlinks to Chapters 20 and 21 of "The C + + Programming Language" (4th Edition, by Bjarne Stroustrup) link instead to internal C++ Crash Course chapters.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#79]
Two hyperlinks in the note box on page 137 seem like they were intended to link to pages that are related to Chapters 20 and 21 of "The C + + Programming Language" (4th Edition, by Bjarne Stroustrup) but instead link to internal chapters of the C++ Crash Course book.

Perhaps an automated system in your book creation software added these in for you incorrectly, in an attempt to be "helpful".

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
