### ISSUE TITLE
Page 149: Martha Stewart quote at top of chapter 6 is misquoted. It has a typo.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#80]
The current quote reads:

> The more adapt, the more interesting you are.

... but it should instead be:

> The more **you** adapt, the more interesting you are.

I debated posting this, since I promised to only post more substantive errors here, but I figured that a misquote of someone else's words may count for those purposes. It's a bit debatable I suppose. As such, hopefully this report is acceptable and not too low value to post here.

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks for reporting! It seems this is only on certain ebook formats but not in the PDF or printed version. Good catch!
