### ISSUE TITLE
Page 167: Description of concept Averagable says it uses two type traits when it actually only uses one.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#81]
In the following text:

> The concept is composed of three Boolean expressions AND-ed (&&) together: **two type traits ➊ ➌ and a requires expression**. If any of the three returns false, the concept’s constraints are not met.

In reality, the corresponding code uses one type trait and one requires containing two requirement expressions.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
