### ISSUE TITLE
Page 175: The text refers to a non-existant exception type named "out_of_bounds".

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#82]
The correct name of the intended exception is "**out_of_range**".

The text that contains the error is as follows:

> The get function accepts a reference to an int array of length 10 ➊ and an index to extract ➋. If index is out of bounds, it throws an **out_of_bounds** exception ➌; otherwise, it returns a reference to the corresponding element ➍.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
