### ISSUE TITLE
Page 200: The text states that the address of int x prints 0, which is wrong.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#84]
In the following text:

> The address refers to the address of x ➊ and prints 0 ➋.

The statement is wrong as worded.

The code actually prints a non-zero address for x (in this case 0x000000F79DCFFB74), but then later also prints a nullptr as a hex string which ends up being 0x0000000000000000.

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
