### ISSUE TITLE
Page 187, Listing 7-2, "std::runtime_error" should read "std::overflow_error"

### ISSUE THREAD

**Issue by Scicomath** [JLospinoso/ccc#9]
The Listing 7-2 in the book is inconsistent with code in [Listing 7-3 at Github](https://github.com/JLospinoso/ccc/blob/master/chapter_7/listing_7_3.cpp). 

The "std::runtime_error" should read "std::overflow_error".

**Comment by JLospinoso** [comment]
Thanks @Scicomath!
