### ISSUE TITLE
There's an error on the errata page itself. Wrong/meaningless: p. 277 Exercise 9-3, "template " should read "template "

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#91]
The following piece of text on the errata page actually itself contains an error:

`"p. 277 Exercise 9-3, "template " should read "template "`

This correction is meaningless/redundant. The word "template" is not misspelled on the page.

The errata info for this item does not reflect the real error that was originally reported for that case, see: https://github.com/JLospinoso/ccc/issues/45

...

Another thought: Template parameter delimiters <...> sure do look a lot like HTML tags.   ; )

**Comment by JLospinoso** [comment]
Thanks, @WraithGlade!
