### ISSUE TITLE
Page 41: %zu is a better format specifier for size_t than %zd

### ISSUE THREAD

**Issue by delan** [JLospinoso/ccc#93]
size_t is an unsigned type, so %zd would be misleading for many values:

```c++
#include <cstdint>
#include <cstdio>
int main() { printf("%zd", SIZE_MAX); }
```

**Comment by JLospinoso** [comment]
Thanks @delan! This is a pretty major erratum. I've added a note for the first occurrence on Page 41, but it needs to be fixed all over the place.
