### ISSUE TITLE
Page 402: boost::convert and boost::converter instead of boost::numeric::converter

### ISSUE THREAD

**Issue by cetetesoft** [JLospinoso/ccc#97]

**Comment by JLospinoso** [comment]
Thanks, @cetetesoft!

**Comment by JLospinoso** [comment]
Hi @cetetesoft, could you provide a little more information for me? What's the problem with `boost::numeric::converter`?

**Comment by cetetesoft** [comment]
Hi, @JLospinoso. It's just that sometimes it says ```boost::converter``` (without ```numeric::```).

Also, on the next page there's a ```boost::boost::numeric_cast``` in listing 12-36. I think it should be ```boost::numeric_cast```.

**Comment by JLospinoso** [comment]
Thanks, @cetetesoft! I see what you mean.
