### ISSUE TITLE
Page 342 and 344 (and elsewhere): The way you are using Catch.hpp will cause massive compilation slowdowns for anyone who mimics you.

### ISSUE THREAD

**Issue by WraithGlade** [JLospinoso/ccc#99]
The catch.hpp header file for unit testing is a **17'000+ line** header file and takes quite a long time to compile. Any file you where you both `#include` the `catch.hpp` and define the `CATCH_CONFIG_MAIN` pre-processor symbol will be **forced to recompile all 17'000 lines of catch.hpp every single time you make even the smallest change to the file you have it in**. You are not using the header file the way the developers of that unit testing framework intended it.

If you read the documentation more fully, you will see that they advise you to place the preamble in its own file, with nothing else ideally, and then to thereafter minimize changes to that file (and thus also to minimize any changes to any other files included in it too, due to C++'s simplistic text substitution compilation model). By doing so, the catch.hpp will only ever have to be compiled once for most use cases. This will makes the extent to which Catch slows down build times vastly less than the way you are currently using it. When properly set up like this, the compilation burden isn't even hardly noticeable on small projects.

Here are two good options for what main.cpp should look like if you are using Catch correctly. I've also added warnings in comments and some minor style change according to my own preferences. Hopefully some people reading the book will find it helpful for a faster and/or more controllable workflow:

Option A (auto-generation of main function):

```
// main.cpp

// Everytime you modify this file in any way, 
// all 17'000+ lines of catch.hpp must be recompiled.
// Minimize how much you touch this file 
// and also any other files #included in it.

#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

Option B (ability to modify main function):

```
// main.cpp

// Everytime you modify this file in any way, 
// all 17'000+ lines of catch.hpp must be recompiled.
// Minimize how much you touch this file 
// and also any other files #included in it.

#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main(const int cmd_arg_count, const char* cmd_args[])
{
	const int Catch_exit_status_code = Catch::Session().run(cmd_arg_count, cmd_args);

	return Catch_exit_status_code;
}
```

After creating a main.cpp file like this (either option), you can simply define test files in other cpp files in your project and they will run automatically with no further effort. For example, I used a file named "test.cpp" to put all my tests in. This way, compilation is vastly faster.

You should probably tell the readers about this pitfall somewhere. **Pages 342 and 344 will mislead many readers into using the header incorrectly.**

**Comment by JLospinoso** [comment]
Hi @WraithGlade, thanks for your ticket! I've designed listings to optimize readability over compile times, and as designed they allow a reader to turn most listings into executable programs with little effort. 

I think it would be worth adding a note that in production you should not make an executable per unit test. I'll see if we can do this in the next printing.

**Comment by WraithGlade** [comment]
Sure, whatever feels best to you for the experience you're going for.

As for anyone else reading the issue tracker on GitHub who still wants a faster workflow though, I will leave one final comment on the matter:

You shouldn't be producing one executable per test anyway, not even when learning from a tutorial. That will only slow down the learning workflow because it would require you to potentially constantly delete stuff you aren't using anymore. It is better to just put all your tests in one project per chapter and to separate those tests from the code body of catch.hpp to speed up learning and iteration times for following tutorials. It's also better to practice good code quality now instead of later, so that good coding and organization habits are reinforced better instead of reinforcing sloppy habits. Steady-handed and careful is almost always more productive and faster overall than being rushed and sloppy in programming, even in tutorials.

For another related example, outside the context of unit testing, when trying out different sequences of instructions, there is no reason to ever keep repeatedly deleting the content of the main function and re-writing it. You should instead define a separate void function for every separate sequence of tutorial instructions you want to test and then just call those functions in main whenever you feel like testing them again.  That's a better way of organizing things and is a more modular way of thinking and is far faster and easier than artificially limiting yourself to a much worse workflow all for the sake of avoiding the extremely small overhead of just organizing your code properly instead.

Anyway, those are my personal thoughts on the matter, for the benefit of anyone who still would prefer to have a more effective workflow even for when working through tutorials, both in the context of this book and in other tutorials. Hopefully it will help someone who sees this.

**Comment by JLospinoso** [comment]
FWIW, the companion code is organized with one test binary per chapter. See e.g. https://github.com/JLospinoso/ccc/blob/master/chapter_11/smart_ptrs.cpp
